2.6.1: Configure scheduler.

diff --git a/1-configure-scheduler b/1-configure-scheduler
--- a/1-configure-scheduler
+++ b/1-configure-scheduler
@@ -5,7 +5,7 @@
 # Configure a scheduler node for the OpenFOAM application profile.
 #
 
-EXPECTED_SOCA_VERSION=2.5.0
+EXPECTED_SOCA_VERSION=2.6.1
 EXPECTED_BASE_OS=amazonlinux2
 
 SOCA_HOME="/apps/soca/$SOCA_CONFIGURATION"
@@ -57,23 +57,23 @@ echo "Stop cluster_web_ui"
 pushd "$SOCA_HOME/cluster_web_ui" || exit 1
 ./socawebui.sh stop || exit 1
 
-echo "Patch SOCA"
-pushd "$SOCA_HOME" || exit 2
+# echo "Patch SOCA"
+# pushd "$SOCA_HOME" || exit 2
 
-patch -p2 < "$SCRIPT_DIR/soca/patches/job_output_path.patch"
-if [ $? -ne 0 ] ; then
-    echo "WARNING: soca_job_output-path.patch failed to apply. job_output_path will not be available in scripts."
-    echo "Continue (y/n)?"
-    read RSP
-    RSP="$(echo $RSP | tr '[A-Z]' '[a-z]')"
-    if [ "$RSP" != "y" ] ; then
-	echo "Quit"
-	exit 1
-    fi
-fi
-patch -p2 < "$SCRIPT_DIR/soca/patches/fixed_vcpus_check_limits.patch" || exit 1
+# patch -p2 < "$SCRIPT_DIR/soca/patches/job_output_path.patch"
+# if [ $? -ne 0 ] ; then
+#     echo "WARNING: soca_job_output-path.patch failed to apply. job_output_path will not be available in scripts."
+#     echo "Continue (y/n)?"
+#     read RSP
+#     RSP="$(echo $RSP | tr '[A-Z]' '[a-z]')"
+#     if [ "$RSP" != "y" ] ; then
+# 	echo "Quit"
+# 	exit 1
+#     fi
+# fi
+# patch -p2 < "$SCRIPT_DIR/soca/patches/fixed_vcpus_check_limits.patch" || exit 1
 
-popd
+
 SQL_BK="$(mktemp db.sqlite.XXXXX)"
 echo "Backup db.sqlite to $SQL_BK"
 cp db.sqlite "$SQL_BK" || exit 1
@@ -88,4 +88,5 @@ sed  -i ':a;N;$!ba; s/root_size:\s*"10"/root_size: "20"/2' "$SOCA_HOME/cluster_m
 echo "Start cluster_web_ui"
 ./socawebui.sh start || exit 1
 
+popd
 echo "Configuration of $SOCA_CONFIGURATION $(hostname) complete"
